# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 11:08
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('actors', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('director', models.CharField(max_length=25)),
                ('length', models.TimeField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='articles')),
                ('release_date', models.DateField()),
                ('rented', models.BooleanField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='title', unique_with=['title'])),
                ('synopsis', models.TextField()),
                ('trailer_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='movierent',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video_bank.Movie'),
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
