# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_bank', '0002_auto_20181105_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, to='video_bank.MovieGenre'),
        ),
    ]
